defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$trBI0LFn$opiVn.flisvqKUGykGIdb."] 
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[api]
entrypoint="dashboard"

[acme] 
email = "mail@csaladen.es" 
storage = "acme.json" 
entryPoint = "https" 
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[docker] 
domain = "csaladen.es" 
watch = true
network = "web"
